import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Web motor test assignment",
  description: "Generated by create next app",
};

const ceraPro = localFont({
  src: [
    {
      path: "fonts/cera_pro/CeraPro-Regular.woff",
      weight: "400",
    },
    { path: "fonts/cera_pro/CeraPro-Medium.woff", weight: "500" },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ceraPro.className}>
      <body>{children}</body>
    </html>
  );
}
